### ISSUE TITLE
Triggers does not fire at all

### ISSUE THREAD

**Issue by ajagelund** [martijnpoppen/homey-network-check#3]
This is code to diagnostics: 2ad602e5-0503-4b94-9385-1f5ea440b984

**Comment by ajagelund** [comment]
No triggers fires. I get the initial trigger (connection_restored) on the first connection check when running in debug, but no event is fired when installing the app.

**Comment by Dgh1974** [comment]
Same here. Will this app be updated or reworked because i can realy use it to restart my router

**Comment by gvanlee** [comment]
Slow response, sorry.

Will look into the problem. It's probably because the app has not been updated for the SDK 2 release.

**Comment by Dgh1974** [comment]
Hope you can fix so i can testart my router once connection is lost

Verstuurd vanaf mijn iPhone X

Op 24 aug. 2019 om 16:55 heeft Gabri van Lee <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Slow response, sorry.

Will look into the problem. It's probably because the app has not been updated for the SDK 2 release.

**Comment by Dgh1974** [comment]
Are u working on it or wont it be updated ?

**Comment by gvanlee** [comment]
Updated version is being tested but seems too memory hungry. Should be
released in a couple of weeks.

Op za 28 sep. 2019 om 11:28 schreef Dgh1974 <notifications@github.com>:

**Comment by Dgh1974** [comment]
Hi Gabri

Is it correct that 0.2.0 update arrived a week ago ? 

Its not working for me unfortunatly. When switch my modem off i get no notification (flow =  if no connection ... then send the “no internet” notification ). i did create that flow just to test if the app works.

Send Notifications should be visible in the app after connection is re-established ( notification that is ... NO push message )
