### ISSUE TITLE
SDK v3

### ISSUE THREAD

**Issue by martijnpoppen** [martijnpoppen/homey-network-check#5]
Hi
Are you planning to update to SDK v3?
If not are you willing to transfer this app?

Please let me know :)

**Comment by gvanlee** [comment]
Apologies for the slow response, feel free to take over, I am too busy to figure out what to change.

 

Kind regards, 

Gabri

 

Van: Martijn Poppen ***@***.***> 
Verzonden: woensdag 2 november 2022 01:42
Aan: gvanlee/homey-network-check ***@***.***>
CC: Subscribed ***@***.***>
Onderwerp: [gvanlee/homey-network-check] SDK v3 (Issue #5)

 

Hi
Are you planning to update to SDK v3?
If not are you willing to transfer this app?

Please let me know :)

**Comment by martijnpoppen** [comment]
Ah super thanks!

You can transfer the app to: 5e2daad2e3e0da0ca754b6a8

Via the developer portal you can transfer the app.
I saw you already forwarded the repo to me :)
